import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { GifLayout } from "~/components/GifLayout";
import { useGiphy } from "~/hooks/useGiphy";

const Home: NextPage = () => {
  const { gifs, fetchGifs } = useGiphy();
  const [inputValue, setInputValue] = useState("");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen justify-center bg-slate-900 align-middle">
        <form
          className="max-w-5xl flex-col justify-center align-middle"
          onSubmit={(e) => {
            e.preventDefault();
            fetchGifs(inputValue).catch((error) => {
              console.error("Error:", error);
            });
          }}
        >
          <h2 className="text-xl font-semibold text-slate-300">
            Search for your favorite gifs!
          </h2>
          <input
            type="text"
            placeholder="Tip: Cats are always a good search"
            className="w-full"
            onChange={(e) => setInputValue(e.target.value)}
            value={inputValue}
          />
        </form>
        <GifLayout gifs={gifs} />
      </main>
    </>
  );
};

export default Home;
